apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: myapp
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9376
  selector:
    app: myapp
    tier: frontend
